import type { LouBadge, LouLocale, LouResult } from "./lou.js";
export type LouRarity="common"|"rare"|"epic"|"legendary";
export interface LouAchievement extends LouBadge { rarity:LouRarity; hidden?:boolean; progress:number; target:number; }
export interface LouCollection { namespace:string; achievements:LouAchievement[]; }
export interface LouEvent { type:"lou:gradeChanged"|"lou:badgeUnlocked"|"lou:newHighScore"|"lou:maximumLou"; result:LouResult; achievement?:LouAchievement; }
const collections=new Map<string,LouCollection>();
export function registerLouCollection(collection:LouCollection){if(!collection.namespace||collections.has(collection.namespace))throw new Error("Lou collection namespace already exists.");collections.set(collection.namespace,collection)}
export function listLouCollections(){return [...collections.keys()].sort()}
export function getLouAchievements(result:LouResult):LouAchievement[]{return result.badges.map(b=>({...b,rarity:b.id==="maximum"?"legendary":b.id==="vibe"?"rare":"common",progress:1,target:1}))}
export function createLouSession(initial:LouResult[]=[]){let items=[...initial],listeners=new Set<(event:LouEvent)=>void>();const emit=(event:LouEvent)=>listeners.forEach(l=>l(event));return{add(result:LouResult){const previous=items.at(-1);items.push(result);if(!previous||result.score>Math.max(...items.slice(0,-1).map(x=>x.score)))emit({type:"lou:newHighScore",result});if(previous&&previous.grade!==result.grade)emit({type:"lou:gradeChanged",result});for(const achievement of getLouAchievements(result))emit({type:"lou:badgeUnlocked",result,achievement});if(result.grade==="MAXIMUM LOU")emit({type:"lou:maximumLou",result});return result},on(listener:(event:LouEvent)=>void){listeners.add(listener);return()=>listeners.delete(listener)},summary(){const scores=items.map(x=>x.score),best=Math.max(0,...scores);return{count:items.length,best,personalBest:items.find(x=>x.score===best),average:scores.length?scores.reduce((a,b)=>a+b,0)/scores.length:0,trend:(scores.at(-1)??0)-(scores[0]??0),milestone:best>=95?"maximum":best>=70?"high":"warming-up"}},results:()=>[...items]}}
const pick=(seed:string|number|undefined,values:string[])=>values[Math.abs([...String(seed??0)].reduce((n,c)=>n*31+c.charCodeAt(0),7))%values.length];
export function seededLouMessage(result:LouResult,seed?:string|number,locale:LouLocale="en"){const choices=locale==="hu"?["A Lou-mérő stabil.","Játékos csúcsenergia.","A vibe tovább emelkedik."]:["Lou levels nominal.","Playful peak energy.","Vibe remains elevated."];return `${pick(seed,choices)} ${result.grade}.`}
export function formatLouText(result:LouResult){return `${result.presentation.title} — ${result.presentation.narrative}`}
export function formatLouMarkdown(result:LouResult){return `## ${result.presentation.title}\n\n${result.presentation.narrative}\n\n${result.badges.map(b=>`${b.emoji} ${b.label}`).join(" · ")}\n\n_${result.presentation.disclaimer}_`}
export function formatLouTerminal(result:LouResult,ansi=false){const bar="█".repeat(Math.round(result.score/10))+"░".repeat(10-Math.round(result.score/10));const text=`${bar} ${result.score.toFixed(0)} ${result.grade}`;return ansi?`\x1b[35m${text}\x1b[0m`:text}
export function exportLouResult(result:LouResult){return JSON.stringify({schemaVersion:1,result})}
export function importLouResult(json:string):LouResult{const value=JSON.parse(json);if(value.schemaVersion!==1)throw new Error("Unsupported Lou snapshot version.");return value.result}
export function louProtocol(result?:LouResult,seed?:string|number){if(!result)return{code:503,error:"LOU_UNAVAILABLE",message:"Insufficient Lou exposure.",disclaimer:"Unofficial fan/parody protocol."};return{code:200,lou:Math.round(result.score),state:result.grade.replaceAll(" ","_"),message:seededLouMessage(result,seed),disclaimer:"Unofficial fan/parody protocol."}}
